# Generated by Django 3.1.2 on 2020-11-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='user-icon.png', upload_to='profiles/'),
        ),
    ]
