# Generated by Django 3.1.2 on 2020-11-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201130_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='user-icon.png', null=True, upload_to='profiles/'),
        ),
    ]
