# Generated by Django 3.1 on 2020-10-15 14:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=300)),
                ('category', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 10, 15, 14, 56, 10, 746188, tzinfo=utc))),
                ('appointment_date', models.DateTimeField()),
                ('image_url', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('attendees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
