# Generated by Django 3.1 on 2020-11-07 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=300)),
                ('category', models.CharField(choices=[('', '----------'), ('eating', 'Eating'), ('sport', 'Sport'), ('party', 'Party')], default='', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment_date', models.DateTimeField()),
                ('image_url', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
