# Generated by Django 3.1 on 2020-10-15 14:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 15, 14, 56, 49, 61482, tzinfo=utc)),
        ),
    ]
