# Generated by Django 3.1 on 2020-10-23 05:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_auto_20201023_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.TextField(choices=[('', '----------'), ('nonworking', "Something isn't Working"), ('sexual_abusive', 'Sexually explicit event'), ('spam', 'Spam or scam'), ('hate_speech', 'Hate Speech'), ('violence', 'Violence or Harmful event')], default='', max_length=15)),
                ('detail', models.TextField(max_length=500)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
