# Generated by Django 3.1 on 2020-10-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20201025_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('', '----------'), ('non-working', "Something isn't Working"), ('sexual-abusive', 'Sexually explicit event'), ('spam', 'Spam or scam'), ('hate-speech', 'Hate Speech'), ('violence', 'Violence or Harmful event')], default='', max_length=15),
        ),
    ]
